CRITICAL - 2020-09-08 18:56:31 --> Undefined index: ativo
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(108): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 108, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(48): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('atualizar-usuar...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-09-08 18:56:31 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-09-08 18:56:57 --> oci_execute(): ORA-12899: value too large for column &quot;ARTHUR&quot;.&quot;USUARIO&quot;.&quot;ATIVO&quot; (actual: 12, maximum: 1)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 130, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(130): oci_execute(Resource id #105)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(110): App\Models\M_Usuario->AtualizarUsuario('63')
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(48): App\Controllers\Usuario->AtualizarUsuario(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('atualizar-usuar...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-09-08 18:56:57 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-09-08 19:00:28 --> oci_execute(): ORA-12899: value too large for column &quot;ARTHUR&quot;.&quot;USUARIO&quot;.&quot;ATIVO&quot; (actual: 12, maximum: 1)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 130, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(130): oci_execute(Resource id #105)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(110): App\Models\M_Usuario->AtualizarUsuario('63')
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(48): App\Controllers\Usuario->AtualizarUsuario(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('atualizar-usuar...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-09-08 19:00:28 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-09-08 19:11:36 --> Undefined index: ativo
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(64): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 64, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-09-08 19:12:15 --> Undefined index: ativo
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(65): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 65, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-09-08 19:14:19 --> Undefined index: ativo
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(65): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 65, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-09-08 19:15:31 --> oci_execute(): ORA-12899: value too large for column &quot;ARTHUR&quot;.&quot;USUARIO&quot;.&quot;ATIVO&quot; (actual: 12, maximum: 1)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 133, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(133): oci_execute(Resource id #105)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(110): App\Models\M_Usuario->AtualizarUsuario('63')
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(48): App\Controllers\Usuario->AtualizarUsuario(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('atualizar-usuar...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-09-08 19:15:31 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
