CRITICAL - 2020-08-16 11:40:05 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(42): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(30): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:40:07 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(42): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(30): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:40:21 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(42): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(30): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:40:48 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:40:50 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:40:52 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:40:52 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:41:19 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:41:20 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:43:56 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:43:58 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:43:58 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:44:00 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:44:00 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:44:00 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:44:01 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:44:01 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:44:01 --> Undefined variable: conectar
#0 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:46:29 --> oci_parse() expects parameter 1 to be resource, int given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_parse() exp...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Setor.php(26): oci_parse(231, 'SELECT setor_se...')
#2 C:\xampp\htdocs\arthur\app\Models\M_Setor.php(14): App\Models\M_Setor->SequencieSetor()
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(48): App\Models\M_Setor->CadastraSetor()
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:46:32 --> oci_parse() expects parameter 1 to be resource, int given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_parse() exp...', 'C:\\xampp\\htdocs...', 26, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Setor.php(26): oci_parse(231, 'SELECT setor_se...')
#2 C:\xampp\htdocs\arthur\app\Models\M_Setor.php(14): App\Models\M_Setor->SequencieSetor()
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(48): App\Models\M_Setor->CadastraSetor()
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:32 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:36 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:37 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:37 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:37 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:37 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:38 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:38 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:38 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:38 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:49:39 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:00 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:01 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:01 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:02 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:02 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:03 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:03 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:03 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:04 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:04 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:04 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:04 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:05 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:05 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:05 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:08 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:09 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:09 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:09 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:09 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:09 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:10 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:10 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:10 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:10 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:11 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:11 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:11 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:50:12 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(31): App\Controllers\Setor->CadastraSetor(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 11:51:20 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(42): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 11:51:41 --> syntax error, unexpected '$conn' (T_VARIABLE)
#0 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\arthur\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\Cone...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\Cone...')
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(42): spl_autoload_call('App\\Models\\Cone...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 11:51:52 --> oci_connect(): ORA-01017: invalid username/password; logon denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\arthur\app\Models\Conexao.php(11): oci_connect('arthur', '12346578', 'localhost/XE')
#2 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): App\Models\Conexao->Conectar()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 11:53:49 --> oci_connect(): ORA-01017: invalid username/password; logon denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\arthur\app\Models\Conexao.php(11): oci_connect('arthur', '12346578', 'localhost/XE')
#2 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): App\Models\Conexao->Conectar()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 11:54:08 --> oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\arthur\app\Models\Conexao.php(11): oci_connect('$username', '$pass', '$host')
#2 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): App\Models\Conexao->Conectar()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 11:54:36 --> Undefined variable: conn
#0 C:\xampp\htdocs\arthur\app\Models\Conexao.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): App\Models\Conexao->Conectar()
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 11:54:45 --> oci_connect(): ORA-01017: invalid username/password; logon denied
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\arthur\app\Models\Conexao.php(12): oci_connect('arthur2', '12345678', 'localhost/XE')
#2 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): App\Models\Conexao->Conectar()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 11:55:28 --> oci_connect(): ORA-12154: TNS:could not resolve the connect identifier specified
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_connect(): ...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\arthur\app\Models\Conexao.php(11): oci_connect('$username', '$pass', '$host')
#2 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(43): App\Models\Conexao->Conectar()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->Teste()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 12:00:38 --> Undefined variable: stid
#0 C:\xampp\htdocs\arthur\app\Models\M_Setor.php(16): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(53): App\Models\M_Setor->CadastraSetor()
#2 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(30): App\Controllers\Setor->CadastraSetor(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('cadastra-setor')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 13:27:12 --> Call to undefined method App\Controllers\Setor::AtualizarSetor()
#0 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('atualiza-setor')
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-08-16 13:29:17 --> Call to undefined method App\Controllers\Setor::AtualizarSetor()
#0 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('atualiza-setor')
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-08-16 13:29:33 --> Call to undefined method App\Controllers\Setor::AtualizarSetor()
#0 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->acao('atualiza-setor')
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-08-16 16:05:44 --> Class 'App\Controllers\M_Usuario' not found
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(34): App\Controllers\Usuario->CadastraUsuario(Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 16:06:27 --> Class 'App\Controllers\M_Usuario' not found
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(34): App\Controllers\Usuario->CadastraUsuario(Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 16:06:31 --> Class 'App\Controllers\M_Usuario' not found
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(34): App\Controllers\Usuario->CadastraUsuario(Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 16:07:44 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(69): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:07:49 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(69): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:08:47 --> Undefined variable: codigo
#0 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(41): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(69): App\Models\M_Usuario->CadastraUsuario()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 16:08:56 --> Undefined variable: codigo
#0 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(41): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(69): App\Models\M_Usuario->CadastraUsuario()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 16:10:54 --> Undefined variable: codigo
#0 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(41): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(69): App\Models\M_Usuario->CadastraUsuario()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 16:14:18 --> Undefined variable: codigo
#0 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(41): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 16:14:38 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:16:52 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastraUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:21:18 --> Undefined variable: codigo
#0 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(41): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 16:21:49 --> Undefined variable: codigo
#0 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(41): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 41, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 16:23:22 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:25:18 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:27:38 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:28:05 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:28:43 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 16:30:46 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 17:00:18 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 17:01:40 --> Object of class App\Models\M_Usuario could not be converted to string
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 17:05:44 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(24): CodeIgniter\Model->__call('SequencieUsuari...', Array)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#4 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 17:06:01 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(24): CodeIgniter\Model->__call('SequencieUsuari...', Array)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#4 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 17:10:11 --> oci_parse(): ORA-01756: quoted string not properly terminated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_parse(): OR...', 'C:\\xampp\\htdocs...', 53, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(53): oci_parse(Resource id #103, '\r\n\t\t\tINSERT INT...')
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(69): App\Models\M_Usuario->CadastraUsuario()
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(35): App\Controllers\Usuario->CadastrarUsuario(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:10:11 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 17:26:18 --> oci_execute(): ORA-00911: invalid character
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 81, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(81): oci_execute(Resource id #107)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): App\Models\M_Usuario->ListaUsuario()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:27:00 --> Undefined index: email_usuario
#0 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(93): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 93, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): App\Models\M_Usuario->ListaUsuario()
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 17:27:14 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:27:34 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:31:19 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:31:33 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:32:45 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:33:04 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:33:09 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:33:13 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:34:21 --> oci_execute(): ORA-00001: unique constraint (ARTHUR.SYS_C007038) violated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 54, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(54): oci_execute(Resource id #106)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(37): App\Controllers\Usuario->CadastrarUsuario(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:34:21 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 17:35:14 --> oci_execute(): ORA-00001: unique constraint (ARTHUR.SYS_C007038) violated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 54, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(54): oci_execute(Resource id #106)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(37): App\Controllers\Usuario->CadastrarUsuario(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:35:14 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 17:35:38 --> oci_execute(): ORA-00001: unique constraint (ARTHUR.SYS_C007038) violated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 54, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(54): oci_execute(Resource id #106)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(71): App\Models\M_Usuario->CadastraUsuario()
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(37): App\Controllers\Usuario->CadastrarUsuario(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('cadastra-usuari...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:35:38 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 17:36:03 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:36:08 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:36:15 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:36:31 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:36:40 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:39:14 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:39:43 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(22): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:40:18 --> You must set the database table to be used with your query.
#0 C:\xampp\htdocs\arthur\system\Model.php(1206): CodeIgniter\Database\BaseConnection->table(NULL)
#1 C:\xampp\htdocs\arthur\system\Model.php(1714): CodeIgniter\Model->builder()
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): CodeIgniter\Model->__call('ListaUsuario', Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 17:41:21 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:41:40 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:41:55 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:42:37 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:42:50 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:43:16 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 17:43:27 --> Invalid argument supplied for foreach()
#0 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-16 18:25:49 --> Class 'Date' not found
#0 C:\xampp\htdocs\arthur\system\View\View.php(246): include()
#1 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 18:25:52 --> Class 'Date' not found
#0 C:\xampp\htdocs\arthur\system\View\View.php(246): include()
#1 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 18:26:08 --> Class 'Date' not found
#0 C:\xampp\htdocs\arthur\system\View\View.php(246): include()
#1 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 18:28:52 --> Class 'Date' not found
#0 C:\xampp\htdocs\arthur\system\View\View.php(246): include()
#1 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 18:28:56 --> Class 'Date' not found
#0 C:\xampp\htdocs\arthur\system\View\View.php(246): include()
#1 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 18:29:03 --> Class 'Date' not found
#0 C:\xampp\htdocs\arthur\system\View\View.php(246): include()
#1 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 18:29:53 --> DateTime::format() expects exactly 1 parameter, 2 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'DateTime::forma...', 'C:\\xampp\\htdocs...', 30, Array)
#1 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(30): DateTime->format(Object(DateTime), 'Y-m-d')
#2 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#4 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 18:30:02 --> DateTime::format() expects exactly 1 parameter, 2 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'DateTime::forma...', 'C:\\xampp\\htdocs...', 30, Array)
#1 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(30): DateTime->format(Object(DateTime), 'Y-m-d')
#2 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#4 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 18:30:08 --> DateTime::format() expects exactly 1 parameter, 2 given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'DateTime::forma...', 'C:\\xampp\\htdocs...', 30, Array)
#1 C:\xampp\htdocs\arthur\app\Views\usuario\usuario.php(30): DateTime->format(Object(DateTime), 'Y-m-d')
#2 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('usuario/usuario', Array, true)
#4 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(25): view('usuario/usuario')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#7 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2020-08-16 18:39:41 --> oci_execute(): ORA-00936: missing expression
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 80, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Usuario.php(80): oci_execute(Resource id #107)
#2 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(20): App\Models\M_Usuario->ListaUsuario()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->index()
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-16 19:31:27 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:31:27 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:32:17 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:32:17 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:33:40 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:33:40 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:33:56 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:33:56 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:34:55 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:34:55 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:35:39 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:35:39 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:35:54 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:35:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:35:57 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:35:57 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:36:33 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('reseta-senha-us...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:36:33 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:38:57 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('resetar-senha-u...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:38:57 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-16 19:39:07 --> Undefined index: nm_nome
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(101): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 101, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarUsuario(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('resetar-senha-u...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 19:39:43 --> Undefined index: nova_senha
#0 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(118): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 118, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Usuario.php(53): App\Controllers\Usuario->AtualizarSenha(Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Usuario->acao('resetar-senha-u...')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 20:29:39 --> Undefined index: arquivo
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(39): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:29:43 --> Undefined index: arquivo
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(39): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:29:53 --> Undefined variable: _FILE
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(39): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:31:27 --> Undefined index: arquivo
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(39): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:36:19 --> Undefined index: arquivo
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(39): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:36:54 --> Undefined index: arquivo
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(39): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 39, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:45:03 --> syntax error, unexpected 'echo' (T_ECHO)
#0 C:\xampp\htdocs\arthur\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('covid/acao/adic...')
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(789): CodeIgniter\Router\Router->handle('covid/acao/adic...')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(360): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:45:21 --> syntax error, unexpected 'echo' (T_ECHO)
#0 C:\xampp\htdocs\arthur\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('covid/acao/adic...')
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(789): CodeIgniter\Router\Router->handle('covid/acao/adic...')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(360): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:46:29 --> syntax error, unexpected 'echo' (T_ECHO)
#0 C:\xampp\htdocs\arthur\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('covid/acao/adic...')
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(789): CodeIgniter\Router\Router->handle('covid/acao/adic...')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(360): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-16 20:58:48 --> Undefined variable: conn
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(72): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 72, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(40): App\Controllers\Covid->CadastraCovid(Array, Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-16 20:59:15 --> Class 'App\Controllers\M_Setor' not found
#0 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-08-16 20:59:26 --> Class 'App\Controllers\M_Setor' not found
#0 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-08-16 21:40:20 --> Undefined variable: usuario
#0 C:\xampp\htdocs\arthur\app\Views\covid\covid.php(46): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('covid/covid', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(22): view('covid/covid')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
